# Generated by Django 6.0.3 on 2026-06-07 22:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_post_options_alter_farmerprofile_profile_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('disease', 'Disease Detection'), ('crop', 'Crop Suggestion'), ('weather', 'Weather Analysis'), ('market', 'Market Analysis'), ('scheme', 'Scheme Info')], max_length=20)),
                ('input_text', models.TextField(blank=True)),
                ('result', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='scans/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GovScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('financial', 'Financial Aid'), ('insurance', 'Crop Insurance'), ('credit', 'Credit'), ('irrigation', 'Irrigation'), ('soil', 'Soil Health'), ('market', 'Market Access'), ('organic', 'Organic Farming'), ('tech', 'Technology')], max_length=20)),
                ('description', models.TextField()),
                ('benefit', models.CharField(max_length=200)),
                ('eligibility', models.TextField(blank=True)),
                ('how_to_apply', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('price', models.IntegerField(help_text='Price per quintal in INR')),
                ('unit', models.CharField(default='Quintal', max_length=20)),
                ('mandi_name', models.CharField(default='National Average', max_length=100)),
                ('state', models.CharField(default='India', max_length=100)),
                ('change_pct', models.FloatField(default=0.0, help_text='% change from yesterday')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['crop_name'],
                'unique_together': {('crop_name', 'mandi_name')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('follow', 'Follow'), ('scheme', 'Scheme Alert'), ('weather', 'Weather Alert'), ('market', 'Market Alert')], max_length=20)),
                ('message', models.CharField(max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, unique=True)),
                ('temp', models.FloatField()),
                ('wind', models.FloatField()),
                ('humidity', models.FloatField(default=0)),
                ('weather_code', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='crop',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='farm',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='crop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='harvest_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='sowing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='status',
            field=models.CharField(choices=[('sowing', 'Sowing'), ('growing', 'Growing'), ('harvested', 'Harvested'), ('failed', 'Failed')], default='growing', max_length=15),
        ),
        migrations.AddField(
            model_name='farm',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='soil_type',
            field=models.CharField(choices=[('alluvial', 'Alluvial'), ('black', 'Black Cotton'), ('red', 'Red & Laterite'), ('sandy', 'Sandy'), ('clay', 'Clay'), ('loamy', 'Loamy'), ('other', 'Other')], default='loamy', max_length=20),
        ),
        migrations.AddField(
            model_name='farm',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(choices=[('update', 'Crop Update'), ('market', 'Market'), ('scheme', 'Scheme'), ('tip', 'Farming Tip'), ('question', 'Question'), ('weather', 'Weather'), ('tech', 'Technology')], default='update', max_length=20),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='crop',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='api.farm'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='production',
            field=models.FloatField(default=0, help_text='Production in kg'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='revenue',
            field=models.FloatField(default=0, help_text='Revenue in INR'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='season',
            field=models.CharField(choices=[('kharif', 'Kharif'), ('rabi', 'Rabi'), ('zaid', 'Zaid')], default='kharif', max_length=10),
        ),
        migrations.AlterField(
            model_name='farm',
            name='area',
            field=models.FloatField(help_text='Area in acres'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.post'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
