# Generated by Django 5.2.15 on 2026-06-08 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_aiscan_govscheme_marketprice_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiscan',
            name='scan_type',
            field=models.CharField(choices=[('leaf_diagnostic', 'Disease Detection'), ('crop', 'Crop Suggestion'), ('weather', 'Weather Analysis'), ('market', 'Market Analysis'), ('scheme', 'Scheme Info')], max_length=20),
        ),
    ]
