# Generated by Django 5.2.15 on 2026-06-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_aiscan_scan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='govscheme',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='marketprice',
            name='crop_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='weathercache',
            name='city',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
